export const AUTOMATION_FORM_UPDATE_TOOL_NAME = "automation_form_update";

/**
 * Action discriminator generated by the SDK for the client-defined automation
 * form tool (`ClientAction_<tool-name>`). Keep this convention centralized.
 */
export const AUTOMATION_FORM_UPDATE_ACTION_KIND =
  `ClientAction_${AUTOMATION_FORM_UPDATE_TOOL_NAME}` as const;
